"""empty message

Revision ID: 0455045ed6d1
Revises: c5e9a36190d3
Create Date: 2025-04-25 01:05:11.454659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0455045ed6d1'
down_revision = 'c5e9a36190d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('harvest_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Not Sold'::character varying"))

    with op.batch_alter_table('reason_for_rejection', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Not Sold'::character varying"))

    with op.batch_alter_table('rejection_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rejection_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rejection_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('rejection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reason_for_rejection', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'Not Sold'::character varying"))

    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'Not Sold'::character varying"))

    with op.batch_alter_table('harvest_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('harvest_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
