"""empty message

Revision ID: 2388e6b2bb1d
Revises: dc1431874c54
Create Date: 2025-03-28 00:25:10.722405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2388e6b2bb1d'
down_revision = 'dc1431874c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planted_crops',
    sa.Column('plant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('days_old', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('tds', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ph_up', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ph_down', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('solution_a', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('solution_b', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('count > 0', name='check_count_positive'),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id'], ),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.drop_table('plant_crops')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_crops',
    sa.Column('plant_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planting_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('count > 0', name='check_count_positive'),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id'], name='plant_crops_greenhouse_id_fkey'),
    sa.PrimaryKeyConstraint('plant_id', name='plant_crops_pkey')
    )
    op.drop_table('planted_crops')
    # ### end Alembic commands ###
