"""add stored email table

Revision ID: 27deef675134
Revises: ff859a099d88
Create Date: 2025-02-22 23:27:16.048900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27deef675134'
down_revision = 'ff859a099d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_email',
    sa.Column('stored_email_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('stored_email_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hardware_components_activity_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['hardware_components.component_id'], ),
    sa.ForeignKeyConstraint(['login_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('hardware_status_activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logs_description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hardware_status_activity_logs', schema=None) as batch_op:
        batch_op.drop_column('logs_description')

    op.drop_table('hardware_components_activity_logs')
    op.drop_table('stored_email')
    # ### end Alembic commands ###