"""empty message

Revision ID: 2877a7443f52
Revises: 83f72e716919
Create Date: 2025-03-18 00:51:21.811952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2877a7443f52'
down_revision = '83f72e716919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_activity_logs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_control_activity_logs', ['log_date', 'pump1', 'pump2', 'exhaust', 'automode', 'logs_description'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('control_activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_control_activity_logs', type_='unique')

    # ### end Alembic commands ###
