"""empty message

Revision ID: 3412ad85433d
Revises: 5bdede8c4362
Create Date: 2025-04-09 19:04:06.792684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3412ad85433d'
down_revision = '5bdede8c4362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('greenhouse_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'greenhouses', ['greenhouse_id'], ['greenhouse_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('greenhouse_id')

    # ### end Alembic commands ###
