"""empty message

Revision ID: 3a11a62c3914
Revises: d157ed167e88
Create Date: 2025-04-13 15:44:33.012641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a11a62c3914'
down_revision = 'd157ed167e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_constraint('sensor_readings_plant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('sensor_readings_component_id_fkey', type_='foreignkey')
        batch_op.drop_column('plant_id')
        batch_op.drop_column('component_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('plant_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sensor_readings_component_id_fkey', 'hardware_components', ['component_id'], ['component_id'])
        batch_op.create_foreign_key('sensor_readings_plant_id_fkey', 'planted_crops', ['plant_id'], ['plant_id'])

    # ### end Alembic commands ###
