"""empty message

Revision ID: 46f46bb685ab
Revises: 19b5c36de431
Create Date: 2025-04-01 19:56:37.563973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f46bb685ab'
down_revision = '19b5c36de431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('greenhouse_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'greenhouses', ['greenhouse_id'], ['greenhouse_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('greenhouse_id')

    # ### end Alembic commands ###
