"""empty message

Revision ID: 4bedad315c10
Revises: cc1a42f3c2ad
Create Date: 2025-04-07 09:34:40.258119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bedad315c10'
down_revision = 'cc1a42f3c2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planted_crops', ['plant_id'], ['plant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###
