"""empty message

Revision ID: 4e23d0110d10
Revises: 4e3ef0e4bb76
Create Date: 2025-04-15 15:40:44.385437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e23d0110d10'
down_revision = '4e3ef0e4bb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('plant_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=False))
        batch_op.create_foreign_key(None, 'planted_crops', ['plant_id'], ['plant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('total_price')
        batch_op.drop_column('plant_name')
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###
