"""empty message

Revision ID: 4e3ef0e4bb76
Revises: 06d6383752b9
Create Date: 2025-04-15 14:25:20.938553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3ef0e4bb76'
down_revision = '06d6383752b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_crops', schema=None) as batch_op:
        batch_op.alter_column('plant_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['plant_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_crops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('plant_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
