"""empty message

Revision ID: 535285e7d0a3
Revises:
Create Date: 2025-02-16 20:47:00.501622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535285e7d0a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_components',
    sa.Column('component_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.Column('componentName', sa.String(length=200), nullable=True),
    sa.Column('date_of_installation', sa.DateTime(), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('model_number', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('hardware_current_status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.Column('lastChecked', sa.DateTime(), nullable=False),
    sa.Column('statusNote', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['hardware_components.component_id'], ),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id'], ),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('hardware_status_activity_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.String(length=200), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['hardware_components.component_id'], ),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hardware_status_activity_logs')
    op.drop_table('hardware_current_status')
    op.drop_table('hardware_components')
    # ### end Alembic commands ###