"""empty message

Revision ID: 59806f252257
Revises: ae35e921be58
Create Date: 2025-04-01 13:10:56.091542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59806f252257'
down_revision = 'ae35e921be58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seedlings_daysOld', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('greenhouse_daysOld', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_days_grown', sa.Integer(), nullable=False))
        batch_op.drop_column('days_old')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_old', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('total_days_grown')
        batch_op.drop_column('greenhouse_daysOld')
        batch_op.drop_column('seedlings_daysOld')

    # ### end Alembic commands ###
