"""empty message

Revision ID: 5f0eb16dc5ec
Revises: bff8dff94413
Create Date: 2025-04-22 21:03:00.723523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0eb16dc5ec'
down_revision = 'bff8dff94413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
