"""empty message

Revision ID: 6cf775a5c332
Revises: 4bedad315c10
Create Date: 2025-04-08 15:24:56.459639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf775a5c332'
down_revision = '4bedad315c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('critical_level')
        batch_op.drop_column('max_total_ml')

    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_total_ml', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('critical_level', sa.Integer(), nullable=False))

    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['login_id'], ['user_id'])

    with op.batch_alter_table('nutrient_controllers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'planted_crops', ['plant_id'], ['plant_id'])

    with op.batch_alter_table('sale_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['login_id'], ['user_id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planted_crops', ['plant_id'], ['plant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plant_id')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('sale_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('login_id')

    with op.batch_alter_table('nutrient_controllers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('user_id')
        batch_op.drop_column('plant_id')

    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('login_id')

    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.drop_column('critical_level')
        batch_op.drop_column('max_total_ml')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_total_ml', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('critical_level', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('total_price')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
