"""empty message

Revision ID: 6fb663f1ee0d
Revises: 3412ad85433d
Create Date: 2025-04-09 20:27:45.559188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb663f1ee0d'
down_revision = '3412ad85433d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_inventory_container_id_fkey', type_='foreignkey')
        batch_op.drop_column('inventory_container_id')

    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['inventory_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_container_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('inventory_inventory_container_id_fkey', 'inventory_container', ['inventory_container_id'], ['inventory_container_id'])

    # ### end Alembic commands ###
