"""empty message

Revision ID: 79ef2ea1827f
Revises: 5f0eb16dc5ec
Create Date: 2025-04-23 01:07:16.292322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ef2ea1827f'
down_revision = '5f0eb16dc5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
