"""rename Inventory to InventoryContainer

Revision ID: 7ebcbc55f0fc
Revises: f9d140e5567f
Create Date: 2025-03-28 09:54:31.001428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebcbc55f0fc'
down_revision = 'f9d140e5567f'
branch_labels = None
depends_on = None


def upgrade():
    # Remove foreign key constraint before dropping the inventory table
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_logs_inventory_id_fkey', type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # Create new inventory_container table
    op.create_table('inventory_container',
        sa.Column('inventory_container_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('greenhouse_id', sa.Integer(), nullable=False),
        sa.Column('ph_up', sa.Integer(), nullable=False),
        sa.Column('ph_down', sa.Integer(), nullable=False),
        sa.Column('solution_a', sa.Integer(), nullable=False),
        sa.Column('solution_b', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id']),
        sa.PrimaryKeyConstraint('inventory_container_id')
    )

    # Now it's safe to drop the inventory table
    op.drop_table('inventory')

    # Modify inventory_logs table to reference inventory_container instead
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_container_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'inventory_container', ['inventory_container_id'], ['inventory_container_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inventory_logs_inventory_id_fkey', 'inventory', ['inventory_id'], ['inventory_id'])
        batch_op.drop_column('inventory_container_id')

    op.create_table('inventory',
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ph_up', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ph_down', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('solution_a', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('solution_b', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id'], name='inventory_greenhouse_id_fkey'),
    sa.PrimaryKeyConstraint('inventory_id', name='inventory_pkey')
    )
    op.drop_table('inventory_container')
    # ### end Alembic commands ###
