"""empty message

Revision ID: 83f72e716919
Revises: 863e0a619682
Create Date: 2025-03-17 10:54:26.243731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f72e716919'
down_revision = '863e0a619682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_activity_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('pump1', sa.Boolean(), nullable=True),
    sa.Column('pump2', sa.Boolean(), nullable=True),
    sa.Column('exhaust', sa.Boolean(), nullable=True),
    sa.Column('automode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_activity_logs')
    # ### end Alembic commands ###
