"""empty message

Revision ID: 863e0a619682
Revises: 27deef675134
Create Date: 2025-03-08 22:00:04.200353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '863e0a619682'
down_revision = '27deef675134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrient_controller_activity_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=200), nullable=True),
    sa.Column('logs_date', sa.DateTime(), nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=True),
    sa.Column('activated_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['nutrient_controllers.controller_id'], ),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_disabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    with op.batch_alter_table('maintenance_activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    with op.batch_alter_table('nutrient_controllers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated_by', sa.String(), nullable=False))
        batch_op.alter_column('dispensed_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrient_controllers', schema=None) as batch_op:
        batch_op.alter_column('dispensed_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('activated_by')

    with op.batch_alter_table('maintenance_activity_logs', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('is_disabled')

    op.drop_table('nutrient_controller_activity_logs')
    # ### end Alembic commands ###
