"""empty message

Revision ID: 94630e7bc43c
Revises: 3a11a62c3914
Create Date: 2025-04-15 08:59:31.307992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94630e7bc43c'
down_revision = '3a11a62c3914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('inventory_item_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=500), nullable=True))
        batch_op.drop_constraint('inventory_item_logs_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('inventory_items_user_id_fkey', type_='foreignkey')

    with op.batch_alter_table('planted_crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_crops', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('plant_name')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_foreign_key('inventory_items_user_id_fkey', 'users', ['user_id'], ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('inventory_item_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('inventory_item_logs_user_id_fkey', 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('user_name')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('user_name')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
