"""empty message

Revision ID: ae35e921be58
Revises: e35aba0ae85c
Create Date: 2025-04-01 12:07:56.787634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae35e921be58'
down_revision = 'e35aba0ae85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_container_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'inventory_container', ['inventory_container_id'], ['inventory_container_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_container_id')

    # ### end Alembic commands ###
