"""empty message

Revision ID: b885e8a4ff9a
Revises: 0455045ed6d1
Create Date: 2025-04-25 01:12:56.246154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b885e8a4ff9a'
down_revision = '0455045ed6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_container_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory_container', ['inventory_container_id'], ['inventory_container_id'])

    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_container_inventory_id_fkey', type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('inventory_container_inventory_id_fkey', 'inventory', ['inventory_id'], ['inventory_id'])

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_container_id')

    # ### end Alembic commands ###
