"""empty message

Revision ID: bff8dff94413
Revises: 3f00bd8ce651
Create Date: 2025-04-19 21:49:26.818447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff8dff94413'
down_revision = '3f00bd8ce651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('sales_harvestId_fkey', type_='foreignkey')
        batch_op.drop_column('harvestId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harvestId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('sales_harvestId_fkey', 'harvests', ['harvestId'], ['harvest_id'])

    # ### end Alembic commands ###
