"""empty message

Revision ID: c0bcbe16e1e5
Revises: 79ef2ea1827f
Create Date: 2025-04-24 22:35:51.316010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0bcbe16e1e5'
down_revision = '79ef2ea1827f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('harvest_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('SOLD', 'NOT_SOLD', name='salestatusenum'), server_default='Not Sold', nullable=False))

    with op.batch_alter_table('reason_for_rejection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('SOLD', 'NOT_SOLD', name='salestatusenum'), server_default='Not Sold', nullable=False))

    with op.batch_alter_table('rejection_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rejection_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rejection_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('rejection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reason_for_rejection', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('harvest_activity_logs', schema=None) as batch_op:
        batch_op.alter_column('harvest_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('login_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
