"""harvest activity logs table

Revision ID: c217d7a2f2ed
Revises: 2d763169c4d2
Create Date: 2025-02-17 22:52:06.866004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c217d7a2f2ed'
down_revision = '2d763169c4d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvest_activity_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('harvest_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.harvest_id'], ),
    sa.ForeignKeyConstraint(['login_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harvest_activity_logs')
    # ### end Alembic commands ###