"""empty message

Revision ID: cc1a42f3c2ad
Revises: 30eacef50ec8
Create Date: 2025-04-04 00:20:35.160569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc1a42f3c2ad'
down_revision = '30eacef50ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_total_ml', sa.Integer(), nullable=False))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sale_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_message', sa.String(length=255), nullable=False))
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.drop_column('price')
        batch_op.drop_column('description')
        batch_op.drop_column('quantity')
        batch_op.drop_column('item')
        batch_op.drop_column('change_type')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originalPrice', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('currentPrice', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('harvestId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cropDescription', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('salesDate', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_foreign_key(None, 'harvests', ['harvestId'], ['harvest_id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('price')
        batch_op.drop_column('item')
        batch_op.drop_column('sold_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('item', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('salesDate')
        batch_op.drop_column('cropDescription')
        batch_op.drop_column('harvestId')
        batch_op.drop_column('currentPrice')
        batch_op.drop_column('originalPrice')

    with op.batch_alter_table('sale_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('item', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('log_message')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('max_total_ml')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
