"""add isNewUser boolean in user table

Revision ID: ceb00928544e
Revises: 73e4f5b7fef5
Create Date: 2025-02-20 21:02:00.747776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb00928544e'
down_revision = '73e4f5b7fef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isNewUser', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isNewUser')

    # ### end Alembic commands ###