"""empty message

Revision ID: d157ed167e88
Revises: 6fb663f1ee0d
Create Date: 2025-04-09 22:00:18.611869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd157ed167e88'
down_revision = '6fb663f1ee0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('max_total_ml', sa.Integer(), nullable=False))
        batch_op.drop_constraint('inventory_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.drop_column('max_total_ml')

    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_logs_login_id_fkey', type_='foreignkey')
        batch_op.drop_column('login_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('inventory_logs_login_id_fkey', 'users', ['login_id'], ['user_id'])

    with op.batch_alter_table('inventory_container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_total_ml', sa.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('inventory_user_id_fkey', 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('max_total_ml')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
