"""empty message

Revision ID: d68efb24eb4a
Revises: d699e62ee04f
Create Date: 2025-04-15 23:24:08.979195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68efb24eb4a'
down_revision = 'd699e62ee04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reason_for_rejection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('deduction_rate', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.drop_column('too_small')
        batch_op.drop_column('diseased')
        batch_op.drop_column('physically_damaged')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reason_for_rejection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physically_damaged', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('diseased', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('too_small', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_price')
        batch_op.drop_column('deduction_rate')
        batch_op.drop_column('quantity')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
