"""empty message

Revision ID: d699e62ee04f
Revises: 4e23d0110d10
Create Date: 2025-04-15 23:02:48.193067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd699e62ee04f'
down_revision = '4e23d0110d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvests', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
