"""empty message

Revision ID: d6a9d494c44c
Revises: 46f46bb685ab
Create Date: 2025-04-01 20:17:49.349542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a9d494c44c'
down_revision = '46f46bb685ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_container_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_container_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('item', sa.String(length=50), nullable=False),
    sa.Column('old_quantity', sa.Integer(), nullable=True),
    sa.Column('new_quantity', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['inventory_container_id'], ['inventory_container.inventory_container_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_container_logs')
    # ### end Alembic commands ###
