"""empty message

Revision ID: dc1431874c54
Revises: 2877a7443f52
Create Date: 2025-03-24 18:56:22.729189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1431874c54'
down_revision = '2877a7443f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_crops',
    sa.Column('plant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('greenhouse_id', sa.Integer(), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.CheckConstraint('count > 0', name='check_count_positive'),
    sa.ForeignKeyConstraint(['greenhouse_id'], ['greenhouses.greenhouse_id'], ),
    sa.PrimaryKeyConstraint('plant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_crops')
    # ### end Alembic commands ###
