"""empty message

Revision ID: e35aba0ae85c
Revises: 8bd3583b88cc
Create Date: 2025-03-30 21:28:42.604005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35aba0ae85c'
down_revision = '8bd3583b88cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planted_crop_activity_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('logs_description', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['planted_crops.plant_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planted_crop_activity_logs')
    # ### end Alembic commands ###
