"""empty message

Revision ID: ec0d44f8036e
Revises: 97a3307c0f8a
Create Date: 2025-03-28 01:38:21.942772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0d44f8036e'
down_revision = '97a3307c0f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tds_reading', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ph_reading', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('ph_up')
        batch_op.drop_column('ph_down')
        batch_op.drop_column('tds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planted_crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tds', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ph_down', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ph_up', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('ph_reading')
        batch_op.drop_column('tds_reading')

    # ### end Alembic commands ###
